version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ryan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1e20tvu0x0z1b"
s3_prefix = "ryan"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

