AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test App

Parameters:
  Stage:
    Type: String
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/hello_world/
      Handler: app.lambda_handler
      Runtime: python2.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  Internal:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation/internal/custom/template.yaml
      Parameters:
        Stage: !Ref Stage

  API:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation/template_api.yaml
      Parameters:
        Stage: !Ref Stage

  Processing:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation/template_processing.yaml
      Parameters:
        Stage: !Ref Stage
        MyQueueEmailArn: !GetAtt API.Outputs.MyQueueEmailArn
        MyQueueEmailBounceArn: !GetAtt API.Outputs.MyQueueEmailBounceArn
        MySNSTopicEmailBounceArn: !GetAtt API.Outputs.MySNSTopicEmailBounceArn
        MyCustomResourceTestArn: !GetAtt Internal.Outputs.MyCustomResourceTestArn
       
  Storage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation/template_storage.yaml
      Parameters:
        Stage: !Ref Stage

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn