AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String

Resources:

  SetupParamStoreDatabase:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ "-", [ DBTableName, !Ref Stage ]]
      Type: String
      Value: !Join [ "-", [ EmailBlackList, !Ref Stage ]]
      Description: SSM Parameter for getting DB Table name for specific stage.

  # TEST: Create a secret with the username admin and a randomly generated password in JSON.  
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the secret for my RDS instance'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  Internal:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: internal/custom/template.yaml
      Parameters:
        Stage: !Ref Stage

  Tier1API:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: tier1_api/template.yaml
      Parameters:
        Stage: !Ref Stage

  Tier2Processing:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: tier2_processing/template.yaml
      Parameters:
        Stage: !Ref Stage
        MyQueueEmailArn: !GetAtt Tier1API.Outputs.MyQueueEmailArn
        MyQueueEmailBounceArn: !GetAtt Tier1API.Outputs.MyQueueEmailBounceArn
        MyCustomResourceTestArn: !GetAtt Internal.Outputs.MyCustomResourceTestArn

  Tier3Storage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: tier3_storage/template.yaml
      Parameters:
        Stage: !Ref Stage
    DependsOn: SetupParamStoreDatabase