AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String

Resources:

  # Following is an example how to add the SSM ParamStore value via CFM
  # This can be done outside of CFM via:
  # aws ssm put-parameter --name "DBTableName-Dev" --type String --value "EmailBlackListTable-Dev"
  
  # You are not allowed to create a secure-string as this is bad practice to hard-code passwords in CFM
  # aws ssm put-parameter --name "ServicePassword-Dev" --type SecureString --value "pass1234"
  # Then reference it with '{{resolve:ssm-secure:ServicePassword-Dev:1}}' (11 resources take SecureString)

  TestParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ "-", [ DBTableName, !Ref Stage ]]
      Type: String
      Value: !Join [ "-", [ EmailBlackList, !Ref Stage ]]
      Description: SSM Parameter for getting DB Table name for specific stage.

  Internal:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: internal/custom/template.yaml
      Parameters:
        Stage: !Ref Stage

  Tier1API:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: tier1_api/template.yaml
      Parameters:
        Stage: !Ref Stage

  Tier2Processing:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: tier2_processing/template.yaml
      Parameters:
        Stage: !Ref Stage
        MyQueueEmailArn: !GetAtt Tier1API.Outputs.MyQueueEmailArn
        MyQueueEmailBounceArn: !GetAtt Tier1API.Outputs.MyQueueEmailBounceArn
        MyCustomResourceTestArn: !GetAtt Internal.Outputs.MyCustomResourceTestArn

  Tier3Storage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: tier3_storage/template.yaml
      Parameters:
        Stage: !Ref Stage
    DependsOn: TestParameter