AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String
Resources:
  Internal:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ryanjwaters/b8686516e6db890336afd98bfe48de39.template
      Parameters:
        Stage:
          Ref: Stage
  Tier1API:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ryanjwaters/cce528fc618d2812420bce521bae94fa.template
      Parameters:
        Stage:
          Ref: Stage
  Tier2Processing:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ryanjwaters/80d97a91da121ab13a3e4a430835fa76.template
      Parameters:
        Stage:
          Ref: Stage
        MyQueueEmailArn:
          Fn::GetAtt:
          - Tier1API
          - Outputs.MyQueueEmailArn
        MyQueueEmailBounceArn:
          Fn::GetAtt:
          - Tier1API
          - Outputs.MyQueueEmailBounceArn
        MyCustomResourceTestArn:
          Fn::GetAtt:
          - Internal
          - Outputs.MyCustomResourceTestArn
        MyDBTableName:
          Fn::GetAtt:
          - Tier3Storage
          - Outputs.MyDBTableName
  Tier3Storage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ryanjwaters/4c98bd634c89176b3a3e65ba497253f5.template
      Parameters:
        Stage:
          Ref: Stage
