Parameters:
  Stage:
    Type: String

Resources:

  MyQueueEmail: 
    Type: AWS::SQS::Queue
    #Properties: 
      #QueueName: "MyQueueEmail"
  
  MyQueueEmailBounce: 
    Type: AWS::SQS::Queue
    #Properties: 
      #QueueName: "MyQueueEmailBounce"

  MySNSTopicEmailBounce:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            !GetAtt MyQueueEmailBounce.Arn
          Protocol: "sqs"
      TopicName: "ses-bounces-topic-test"
    DependsOn: MyQueueEmailBounce

  MyQueueEmailBouncePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: MyQueuePolicy
        Statement:
        - Sid: Allow-SNS-SendMessage
          Principal: "*"
          Effect: Allow
          Action:
          - sqs:SendMessage
          Resource: !GetAtt MyQueueEmailBounce.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref MySNSTopicEmailBounce
      Queues:
        - !Ref MyQueueEmailBounce
    DependsOn: MySNSTopicEmailBounce

Outputs:

  MyQueueEmailArn:
    Value: !GetAtt MyQueueEmail.Arn

  MyQueueEmailBounceArn:
    Value: !GetAtt MyQueueEmailBounce.Arn

  MySNSTopicEmailBounceArn:
    Value: !Ref MySNSTopicEmailBounce