Parameters:
  Stage:
    Type: String

Resources:

  MyDynamoDBEmailBlacklistTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: '{{resolve:ssm:DBTableName-Dev:1}}'
      AttributeDefinitions: 
        - 
          AttributeName: "EmailAddress"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "EmailAddress"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2